### ISSUE TITLE
Include example Tmuxinator rugular.yml in README

### ISSUE THREAD

**Issue by rreas** [currica/rugular#36]
bundle exec rugular tmux =>

/usr/local/Cellar/ruby/2.2.0/lib/ruby/2.2.0/fileutils.rb:1392:in `initialize': No such file or directory @ rb_sysopen - /Users/rreas/.tmuxinator/rugular.yml (Errno::ENOENT)

**Comment by shicholas** [comment]
I just tested this and it seems to work. do you have a ``~/.tmuxinator`` directory? I'll add something to create it if it doesn't exist.

**Comment by rreas** [comment]
@shicholas Just noting that the missing directory was the issue.
